### Get all books
GET http://localhost:3000/api/books

### Add book
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "Diuna",
  "author": "Frank Herbert",
  "year": 1965
}

### Get book at given ID
GET http://localhost:3000/api/books/7

### Delete book at given ID
DELETE http://localhost:3000/api/books/5




### Create Account
POST http://localhost:3001/api/register
Content-Type: application/json

{
  "email": "user2@email.com",
  "password": "admin"
}

### Log in
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email": "user2@email.com",
  "password": "admin"
}




### Get all of user's orders
GET http://localhost:3002/api/orders/2
Accept: application/json

### Add an order
POST http://localhost:3002/api/orders
Content-Type: application/json

{
  "userID": 2,
  "bookID": 9,
  "quantity": 2
}

### Delete an order
DELETE http://localhost:3002/api/orders/4

### Update an order
PATCH http://localhost:3002/api/orders/1
Content-Type: application/json

{
  "bookID": 6,
  "quantity": 5
}